#!/bin/bash
# Usage: ./lsi-gpio-init

# If needed gpios can be exported during initialization
# All exported gpios have entries under /gpios-state
#for i in {0..27}
#do
#    echo ${i} > /sys/class/gpio/export
#done

