#!/bin/bash
# Usage:
# lsi-gpios-set gpio26=1 gpio27=0 gpio5 gpio6 # gpio5 and gpio6 are exported as inputs

for var in "$@"
do
    echo "Setting $var"
    gpio=`cut -d '=' -f 1 <<< $var`
    val=`cut -d '=' -f 2 <<< $var`
    gpio_num=`grep -oE '([0-9]+)' <<< $gpio`

    if [ ! -d "/sys/class/gpio/gpio${gpio_num}" ] ; then
        echo ${gpio_num} > /sys/class/gpio/export
    fi

    if [ ${val} == "1" ] || [ ${val} == "0" ] ; then
        echo $val > /sys/class/gpio/gpio${gpio_num}/value
        echo out > /sys/class/gpio/gpio${gpio_num}/direction
        echo $val > /sys/class/gpio/gpio${gpio_num}/value
    else
        echo in > /sys/class/gpio/gpio${gpio_num}/direction
    fi
done
