#!/bin/bash
# Usage: ./lsi-gpios-get

# Example: ./lsi-gpios-get
#<gpios-state xmlns="urn:lsi:params:xml:ns:yang:gpios">
#<gpio><name>gpio1</name><level>0</level></gpio>
#...
#<gpio><name>gpio27</name><level>1</level></gpio>
#</gpios-state>

echo '<gpios-state xmlns="urn:lsi:params:xml:ns:yang:gpios">'

for gpio_name in "$@"
do
    val=`gpioget \`gpiofind ${gpio_name}\``

   echo "<gpio><name>${gpio_name}</name><level>${val}</level></gpio>"
done
echo '</gpios-state>'
