#!/usr/bin/python3

import os
import requests
import json
from datetime import datetime, timezone

# Set environment variables for security (recommended) or replace directly
CLIENT_ID = os.getenv("AIRTHINGS_CLIENT_ID", "your_client_id")
CLIENT_SECRET = os.getenv("AIRTHINGS_CLIENT_SECRET", "your_client_secret")
DEVICE_ID = os.getenv("AIRTHINGS_DEVICE_ID", "your_device_serial_number")

# API Endpoints
AUTH_URL = f"https://accounts-api.airthings.com/v1/token"
#API_URL = f"https://airthings.com/{DEVICE_ID}/latest-samples"
API_URL = f"https://ext-api.airthings.com/v1/devices/{DEVICE_ID}/latest-samples"
#API_URL = f"https://ext-api.airthings.com/v1/devices/{DEVICE_ID}"
def get_data():
    """Authenticates and fetches data from Airthings API."""
    # 1. Get Access Token
    auth_response = requests.post(
        AUTH_URL,
        data={"grant_type": "client_credentials"},
        auth=(CLIENT_ID, CLIENT_SECRET),
        timeout=10
    )
    auth_response.raise_for_status()
    token = auth_response.json()["access_token"]

    # 2. Fetch Device Data
    headers = {"Authorization": f"Bearer {token}"}
    data_response = requests.get(API_URL, headers=headers, timeout=10)
    data_response.raise_for_status()
    return data_response.json()

if __name__ == "__main__":
    try:
        data = get_data()
#        print(data)
#        data = json.loads(data_str)
#{'data': {'time': 1785099863, 'battery': 97, 'co2': 778.0, 'humidity': 42.0, 'pm1': 3.0, 'pm25': 3.0, 'pressure': 994.0, 'radonShortTermAvg': 20.0, 'relayDeviceType': 'hub', 'rssi': 0, 'temp': 24.4, 'voc': 393.0}}

    except Exception as e:
        print(f"Error: {e}")

template_str = '''<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware-state"
                xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">
  <last-change>%s</last-change>
  <component>
    <name>airthings</name>
    <class>ianahw:container</class>
    <serial-num>%s</serial-num>
    <mfg-name>Airthings</mfg-name>
    <model-name>View Plus</model-name>
  </component>
  <component>
    <name>temperature</name>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>celsius</value-type>
        <value-scale>milli</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>milli degrees</units-display>
    </sensor-data>
  </component>
  <component>
    <name>co2</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>CO2 level</units-display>
    </sensor-data>
  </component>
  <component>
    <name>humidity</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>percent-RH</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>relative humidity level in percent</units-display>
    </sensor-data>
  </component>
  <component>
    <name>pm1</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>milli</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>PM1 particles</units-display>
    </sensor-data>
  </component>
  <component>
    <name>pm25</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>milli</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>PM25 particles</units-display>
    </sensor-data>
  </component>
  <component>
    <name>voc</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>VOC particles</units-display>
    </sensor-data>
  </component>
  <component>
    <name>pressure</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>air pressure</units-display>
    </sensor-data>
    <name>radon-short-term-average</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>Radon short term average</units-display>
    </sensor-data>
  </component>
</hardware>
'''

json_data_str="{'data': {'time': 1785099863, 'battery': 97, 'co2': 778.0, 'humidity': 42.0, 'pm1': 3.0, 'pm25': 3.0, 'pressure': 994.0, 'radonShortTermAvg': 20.0, 'relayDeviceType': 'hub', 'rssi': 0, 'temp': 24.4, 'voc': 393.0}}"
#data = json.loads(json_data_str.replace("'", '"'))

value_temperature=int(100*float((data['data']['temp'])))
value_co2=int(1*float((data['data']['co2'])))
value_humidity=int(1*float((data['data']['humidity'])))
value_pm1=int(1000*float((data['data']['pm1'])))
value_pm25=int(1000*float((data['data']['pm25'])))
value_pressure=int(1*float((data['data']['pressure'])))
value_radon_short_term_average=int(1*float((data['data']['radonShortTermAvg'])))
value_voc=int(1*float((data['data']['voc'])))

epoch_time=int(data['data']['time'])

dt_object = datetime.fromtimestamp(epoch_time, tz=timezone.utc)
timestamp_str = dt_object.strftime("%Y-%m-%dT%H:%M:%SZ")

str=template_str%(timestamp_str, DEVICE_ID, value_temperature, timestamp_str, value_co2, timestamp_str, value_humidity, timestamp_str, value_pm1, timestamp_str, value_pm25, timestamp_str, value_voc, timestamp_str, value_pressure, timestamp_str, value_radon_short_term_average, timestamp_str)

print(str.replace("\n", ""))

