#!/usr/bin/python3
from bluepy.btle import UUID, Peripheral, Scanner, DefaultDelegate

import os
import sys
import time
import struct
import tableprint
from datetime import datetime, timezone

DEVICE_ID = int(os.getenv("AIRTHINGS_DEVICE_ID", "your_device_serial_number"))

def parseDEVICE_ID(ManuDataHexStr):
    if (ManuDataHexStr == None or ManuDataHexStr == "None"):
        SN = "Unknown"
    else:
        ManuData = bytearray.fromhex(ManuDataHexStr)

        if (((ManuData[1] << 8) | ManuData[0]) == 0x0334):
            SN  =  ManuData[2]
            SN |= (ManuData[3] << 8)
            SN |= (ManuData[4] << 16)
            SN |= (ManuData[5] << 24)
        else:
            SN = "Unknown"
    return SN

class WavePlus():

    
    
    def __init__(self, DEVICE_ID):
        self.periph        = None
        self.curr_val_char = None
        self.MacAddr       = None
        self.SN            = DEVICE_ID
        self.uuid          = UUID("b42e2a68-ade7-11e4-89d3-123b93f75cba")

    def connect(self):
        # Auto-discover device on first connection
        if (self.MacAddr is None):
            scanner     = Scanner().withDelegate(DefaultDelegate())
            searchCount = 0
            while self.MacAddr is None and searchCount < 50:
                devices      = scanner.scan(0.1) # 0.1 seconds scan period
                searchCount += 1
                for dev in devices:
                    ManuData = dev.getValueText(255)
                    SN = parseDEVICE_ID(ManuData)
                    if (SN == self.SN):
                        self.MacAddr = dev.addr # exits the while loop on next conditional check
                        break # exit for loop
            
            if (self.MacAddr is None):
                print("ERROR: Could not find device.")
                print("GUIDE: (1) Please verify the serial number.")
                print("       (2) Ensure that the device is advertising.")
                print("       (3) Retry connection.")
                sys.exit(1)
        
        # Connect to device
        if (self.periph is None):
            self.periph = Peripheral(self.MacAddr)
        if (self.curr_val_char is None):
            self.curr_val_char = self.periph.getCharacteristics(uuid=self.uuid)[0]
        
    def read(self):
        if (self.curr_val_char is None):
            print("ERROR: Devices are not connected.")
            sys.exit(1)            
        rawdata = self.curr_val_char.read()
        rawdata = struct.unpack('<BBBBHHHHHHHH', rawdata)
        sensors = Sensors()
        sensors.set(rawdata)
        return sensors
    
    def disconnect(self):
        if self.periph is not None:
            self.periph.disconnect()
            self.periph = None
            self.curr_val_char = None


NUMBER_OF_SENSORS               = 7
SENSOR_IDX_HUMIDITY             = 0
SENSOR_IDX_RADON_SHORT_TERM_AVG = 1
SENSOR_IDX_RADON_LONG_TERM_AVG  = 2
SENSOR_IDX_TEMPERATURE          = 3
SENSOR_IDX_REL_ATM_PRESSURE     = 4
SENSOR_IDX_CO2_LVL              = 5
SENSOR_IDX_VOC_LVL              = 6

class Sensors():
    def __init__(self):
        self.sensor_version = None
        self.sensor_data    = [None]*NUMBER_OF_SENSORS
        self.sensor_units   = ["%rH", "Bq/m3", "Bq/m3", "degC", "hPa", "ppm", "ppb"]
    
    def set(self, rawData):
        self.sensor_version = rawData[0]
        if (self.sensor_version == 1):
            self.sensor_data[SENSOR_IDX_HUMIDITY]             = rawData[1]/2.0
            self.sensor_data[SENSOR_IDX_RADON_SHORT_TERM_AVG] = self.conv2radon(rawData[4])
            self.sensor_data[SENSOR_IDX_RADON_LONG_TERM_AVG]  = self.conv2radon(rawData[5])
            self.sensor_data[SENSOR_IDX_TEMPERATURE]          = rawData[6]/100.0
            self.sensor_data[SENSOR_IDX_REL_ATM_PRESSURE]     = rawData[7]/50.0
            self.sensor_data[SENSOR_IDX_CO2_LVL]              = rawData[8]*1.0
            self.sensor_data[SENSOR_IDX_VOC_LVL]              = rawData[9]*1.0
        else:
            print("ERROR: Unknown sensor version.\n")
            print("GUIDE: Contact Airthings for support.\n")
            sys.exit(1)
   
    def conv2radon(self, radon_raw):
        radon = "N/A" # Either invalid measurement, or not available
        if 0 <= radon_raw <= 16383:
            radon  = radon_raw
        return radon

    def getValue(self, sensor_index):
        return self.sensor_data[sensor_index]

    def getUnit(self, sensor_index):
        return self.sensor_units[sensor_index]

try:
    #---- Initialize ----#
#    print("Connecting to %s"%(DEVICE_ID))
    waveplus = WavePlus(DEVICE_ID)
    
    header = ['Humidity', 'Radon ST avg', 'Radon LT avg', 'Temperature', 'Pressure', 'CO2 level', 'VOC level']
        
    while True:
        
        waveplus.connect()

        # read values
        sensors = waveplus.read()
        
        waveplus.disconnect()
        
        value_temperature    = int(1000*float(sensors.getValue(SENSOR_IDX_TEMPERATURE)))
        value_co2            = int(sensors.getValue(SENSOR_IDX_CO2_LVL))
        value_humidity       = int(sensors.getValue(SENSOR_IDX_HUMIDITY))
        value_pressure       = int(sensors.getValue(SENSOR_IDX_REL_ATM_PRESSURE))
        value_radon_short_term_average=int(sensors.getValue(SENSOR_IDX_RADON_SHORT_TERM_AVG))
        value_radon_long_term_average=int(sensors.getValue(SENSOR_IDX_RADON_LONG_TERM_AVG))
        value_voc            = int(sensors.getValue(SENSOR_IDX_VOC_LVL))

        epoch_time=int(time.time())

        dt_object = datetime.fromtimestamp(epoch_time, tz=timezone.utc)
        timestamp_str = dt_object.strftime("%Y-%m-%dT%H:%M:%SZ")

        template_str = '''<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware-state"
                xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">
  <last-change>%s</last-change>
  <component>
    <name>airthings</name>
    <class>ianahw:container</class>
    <serial-num>%s</serial-num>
    <mfg-name>Airthings</mfg-name>
    <model-name>View Plus</model-name>
  </component>
  <component>
    <name>temperature</name>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>celsius</value-type>
        <value-scale>milli</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>milli degrees</units-display>
    </sensor-data>
  </component>
  <component>
    <name>co2</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>CO2 level</units-display>
    </sensor-data>
  </component>
  <component>
    <name>humidity</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>percent-RH</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>relative humidity level in percent</units-display>
    </sensor-data>
  </component>
  <component>
    <name>voc</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>VOC particles</units-display>
    </sensor-data>
  </component>
  <component>
    <name>pressure</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>air pressure</units-display>
    </sensor-data>
    <name>radon-short-term-average</name>
    <class>ianahw:sensor</class>
    <parent>airthings</parent>
    <sensor-data>
        <value>%d</value>
        <value-type>other</value-type>
        <value-scale>units</value-scale>
        <value-precision>2</value-precision>
        <value-timestamp>%s</value-timestamp>
        <value-update-rate>60000</value-update-rate>
        <units-display>Radon short term average</units-display>
    </sensor-data>
  </component>
</hardware>
'''
        str=template_str%(timestamp_str, DEVICE_ID, value_temperature, timestamp_str, value_co2, timestamp_str, value_humidity, timestamp_str, value_voc, timestamp_str, value_pressure, timestamp_str, value_radon_short_term_average, timestamp_str)

        print(str.replace("\n", ""))

        break
        
            
finally:
    waveplus.disconnect()

