#!/bin/bash
# Usage:
# lights-set main=FFFFFFFF


for var in "$@"
do
    echo "Setting $var"
    name=`cut -d '=' -f 1 <<< $var`
    val=`cut -d '=' -f 2 <<< $var`

     i2cset -y 1 0x3c 0x01 0x${val:0:2} b
     i2cset -y 1 0x3c 0x02 0x${val:2:2} b
     i2cset -y 1 0x3c 0x03 0x${val:4:2} b

done
