#!/usr/bin/python
import sys
import gpib
import time

# Usage: ./lsi-ivi-dc-power-gpib-e364xa-set [on|off] <voltage-level> <current-limit> ... [on|off] <voltage-level> <current-limit>

# Example: ./lsi-ivi-dc-power-gpib-e364xa-set on 12 0.5 on 13 0.5

def cmd(con, cmd):
	result = ""
	gpib.write(con,cmd)

	while(1):
		c = gpib.read(con,1)
		if(c == b'\n'):
			break
		result +=c.decode("utf-8")

	return result


con=gpib.dev(0,2)



gpib.write(con,'INSTRUMENT:SELECT OUT1\n')
gpib.write(con,'VOLTAGE %s\n'% (sys.argv[2]))
gpib.write(con,'CURRENT %s\n'%(sys.argv[3]))
gpib.write(con,'OUTPUT %s\n'%(sys.argv[1]))
gpib.write(con,'INSTRUMENT:SELECT OUT2\n')
gpib.write(con,'VOLTAGE %s\n'% (sys.argv[5]))
gpib.write(con,'CURRENT %s\n'%(sys.argv[6]))
gpib.write(con,'OUTPUT %s\n'%(sys.argv[4]))
