#!/usr/bin/bash

# Usage: ./lsi-ivi-scope-acquisition-start-dummy <sample-rate> <samples> <trigger-source> <trigger-slope> <trigger-level> <ch1-name> <ch1-range> <ch1-params> ... <chN-name> <chN-range> <chN-params>

# Example: ./lsi-ivi-scope-acquisition-start-dummy 100000 1000 ch1 positive 0.0 ch1 10 - ch2 1 -
