#!/usr/bin/python3

import datetime
import serial
import time
import sys
import math

def log():
	# clear read pipe
	ser.timeout=1
	data = ser.read(1000)
	print(str(data))
	ser.timeout=None

def state():
	# clear read pipe
	ser.timeout=0
	data = ser.read(1000)
	print(data)
	ser.timeout=None
	# status
	ser.write(b'\x8E\x00')
	data = ser.read(26)
	print(data)
	print(data[16])
	print("charge   =%05d mAh" %(data[22]*256*data[23]))
	print("capacity =%05d mAh" %(data[24]*256*data[25]))
	return (data[16])


# Open a serial connection to Roomba
ser = serial.Serial(port='/dev/ttyUSB0', baudrate=115200)

angle = int(sys.argv[1])

print("rotating %d"%(angle))

#max velocity x01\xf4 500 mm/s
#used velocity x00\x64 100 mm/s -> experiment 2 rotations for 11.7 sec
if(angle > 0):

	ser.write(b'\x89\x00\x64\xff\xff') # rotate clockwise
else:

	ser.write(b'\x89\x00\x64\x00\x01') # rotate counter-clockwise
time.sleep((abs(angle)/360)*11.7/2)

print("stop")
ser.write(b'\x89\x00\x00\x00\x00') # back 100 mm/s

# Close the serial port; we're done for now.
ser.close()
