#!/bin/bash

# Usage: ./lsi-ivi-scope-acquisition-start-alsa <sample-rate> <samples> <trigger-source> <trigger-slope> <trigger-level> <ch1-name> <ch1-range> <ch1-params> ... <chN-name> <chN-range> <chN-params>
# Example: ./lsi-ivi-scope-acquisition-start-alsa 48000 480000 - - - "hw:CODEC,0" 4 "-c 2 -f S16_LE"

#Empty. Check lsi-ivi-scope-acquisition-complete-alsa
