#!/usr/bin/python3

# Usage: ./lsi-ivi-scope-acquisition-complete-tektronix-11801b <sample-rate> <samples> <trigger-source> <trigger-slope> <trigger-level> <ch1-name> <ch1-range> <ch1-params> ... <chN-name> <chN-range> <chN-params>

# Example: ./lsi-ivi-scope-acquisition-complete-tektronix-11801b 1000000000000.000000000 1000000 tr0 positive 0.400000000 ch1 2.000000000 0.0

global args
args=None

import sys
import time
import sys
import os
import datetime
import vxi11
import struct

instr = vxi11.vxi11.Instrument("TCPIP::10.0.0.5::gpib,12::INSTR")

# Tektronix 11801B Digital Sampling Oscilloscope 070-8783-01


#instr.write("*IDN?")

samples=2000000

sample_rate=float(sys.argv[1])
samples=int(sys.argv[2])
trigger_source=sys.argv[3]
trigger_slope=sys.argv[4]
trigger_level=float(sys.argv[5])

#print(instr.read())

con = instr

def cmd_binary(instr, cmd):
        instr.write(cmd)
        c = instr.read_raw(4*1024*1024)
        return c

def cmd(instr, cmd):
        result = ""
        instr.write(cmd)
        c = instr.read(4*1024*1024)
        result=c
        #result=c.decode("utf-8")
        return result

def copy_waveform_to_file(trace, filename) :
        type="INT,16"

        con.write('FORMAT:DATA %s\n'%(type))

        block_size_max=1000 # of 1024

        if(sample_rate > 4294967295/2):
            sample_rate_workaround = sample_rate/1000000000
        else:
            sample_rate_workaround = sample_rate

        f1 = open("tmp/lsi-ivi-scope-ch1-signal.wav", "wb")
        f2 = open("tmp/lsi-ivi-scope-ch2-signal.wav", "wb")
        for f in [f1, f2]:
            f.write(bytes([ord('R'), ord('I'), ord('F'), ord('F')]))
            f.write(struct.pack("<I", samples*2+44))
            f.write(bytes([ord('W'),ord('A'),ord('V'),ord('E'),ord('f'),ord('m'),ord('t'),ord(' ')]))
            f.write(struct.pack("<I", 16))
            f.write(struct.pack("<H", 1)) #type 1=PCM
            f.write(struct.pack("<H", 1)) #channels
            f.write(struct.pack("<I", int(sample_rate_workaround)))
            f.write(struct.pack("<I", int(sample_rate_workaround*16*1/8))) #(Sample Rate * BitsPerSample * Channels) / 8
            f.write(struct.pack("<H", 2)) #(BitsPerSample * Channels) / 8.1 - 8 bit mono2 - 8 bit stereo/16 bit mono4 - 16 bit stereo
            f.write(struct.pack("<H", 16)) #Bits per sample
            f.write(bytes([ord('d'),ord('a'),ord('t'),ord('a')]))
            f.write(struct.pack("<I", samples*2))

        con.write("OUT TRA1TOTRA2\n")

        i=0
        for offset in range(0,samples,block_size_max):
            if((offset+block_size_max) > samples):
                block_size=samples-offset
            else:
                block_size=block_size_max

            start = time.time()
            con.write("ACQuisition STOP\n");

            ch=cmd_binary(con, "CURVE?\n");
            print(len(ch))

            end = time.time()
            i=i+1
            print("MAINPOS %fE-8\n"%(2.260+0.1*i))
            con.write("MAINPOS %fE-8\n"%(2.260+0.1*i))
            con.write("ACQuisition RUN\n");
            con.write("CONDACQ TYPE:WAVfrm,WAIT\n");
            time.sleep(1)

            assert(chr(ch[19])=='%')
            print(len(ch[21:-2]))
            f1.write(ch[21:21+2*block_size])
            assert(chr(ch[21+2*block_size+70])=='%')
            f2.write(ch[21+2*block_size+72:21+2*block_size+72+2*block_size])


        for f in [f1, f2]:
            f.close()




channels_num = int((len(sys.argv)-6)/3) 
print (channels_num)
for i in range(0,channels_num):  
    name=sys.argv[6+i*3]
    voltage_range=float(sys.argv[6+i*3+1])
    params=sys.argv[6+i*3+2]
    filename = "tmp/lsi-ivi-scope-%s-signal.wav"%(name)
    copy_waveform_to_file(int(name[2:]), filename)

print("Complete ...")

#con.write('ACQ RUN\n')
#time.sleep(5)
#con.write('ACQ STOP\n')
#con.write("TEX X:1,Y:10,STRING:'http://lightside-instruments.com'\n")
#sys.exit(0)

