#!/usr/bin/python3
import sys
# Usage: ./lsi-ivi-function-generator-set-dummy <on|off> <waveform-type> <frequency> <amplitude> <dc-offset> <duty-cycle>

# Example: ./lsi-ivi-function-generator-set-dummy on square 1634.45 5 2.5 50

print("Starting: %s" %(sys.argv))
