#!/usr/bin/python3

# Usage: ./lsi-ivi-scope-acquisition-start-rigol-ds1054 <sample-rate> <samples> <trigger-source> <trigger-slope> <trigger-level> <ch1-name> <ch1-range> <ch1-params> ... <chN-name> <chN-range> <chN-params>

# Example: ./lsi-ivi-scope-acquisition-start-rigol-ds1054 1000000000.000000000 6000000 ch1 positive 0.600000000 ch1 4.000000000 0.0

global args
args=None

import sys
import time
import sys
import os
import datetime
import vxi11

instr = vxi11.vxi11.Instrument("TCPIP::10.0.0.3::inst0::INSTR")

# Communication interface User's Manual https://scdn.rohde-schwarz.com/ur/pws/dl_downloads/pdm/cl_manuals/user_manual/1335_5337_01/MXO4_UserManual_en_11.pdf


#instr.write("*IDN?")

samples=2000000

sample_rate=float(sys.argv[1])
samples=int(sys.argv[2])
trigger_source=sys.argv[3]
trigger_slope=sys.argv[4]
trigger_level=float(sys.argv[5])

#print(instr.read())

con = instr

def cmd_binary(instr, cmd):
        instr.write(cmd)
        c = instr.read_raw(4*1024*1024)
        return c

def cmd(instr, cmd):
        result = ""
        instr.write(cmd)
        c = instr.read(4*1024*1024)
        result=c
        #result=c.decode("utf-8")
        return result

def setup_channel(channel, voltage_range):
    con.write(':CHANnel'+str(channel)+':PROBe 1\n')
    con.write(':CHAN'+str(channel)+':RANGe %f\n'%(voltage_range))
    con.write(':CHAN'+str(channel)+':COUPLing DC\n')
#    con.write(':CHAN'+str(channel)+':IMPedance %f\n'%(50))
    con.write(':CHAN'+str(channel)+':DISPlay ON\n')

def disable_channel(channel):
        con.write(':CHAN'+str(channel)+':DISPlay OFF\n')


con.write('*RST\n')

time.sleep(5)

reply=cmd(con, '*IDN?')
print (reply)

con.write(':SYSTem:BEEPer OFF\n')

# datetime object containing current date and time
now = datetime.datetime.now()
date_string = now.strftime("%Y/%m/%d")
time_string = now.strftime("%H:%M:%S")

#print(date_string)
#print(time_string)
#con.write('SYSTem:CLOCk:TIME "%s"\n'%(time_string))

print(':TIMebase:SCALe %f\n'%((float(samples)/12)/sample_rate))
con.write(':TIMebase:SCALe %f\n'%((float(samples)/12)/sample_rate))

disable_channel(1)
disable_channel(2)
disable_channel(3)
disable_channel(4)


channels_num = int((len(sys.argv)-6)/3)
print (channels_num)
for i in range(0,channels_num):
    name=sys.argv[6+i*3]
    voltage_range=float(sys.argv[6+i*3+1])
    params=sys.argv[6+i*3+2]

    setup_channel(int(name[2:]),voltage_range)

if(trigger_source != "-"):
    con.write(':TRIGger:EDGe:SOURce CHANnel%d\n'%(int(trigger_source[2:])))
    con.write(':TRIGger:EDGe:LEVel %f\n'%(trigger_level))

    if (trigger_slope=='negative'):
        slope_str='NEGative'
    else:
        slope_str='POSitive'
        con.write(':TRIGger:EDGe:SLOPe %s\n'%(slope_str))

con.write(':ACQuire:MDEPth %d\n'%(samples))

con.write(':TRIGger:SWEep SINGLe\n')

print("Started ...")

#while(1):
#    reply=cmd(con, 'ACQuire:AVAilable?\n')
#    print (reply)
#    time.sleep(1)

