#!/usr/bin/python3
import sys
import time
import vxi11

# Usage: ./lsi-ivi-dc-power-gpib-ember-set <visa-resource-name> <on|off> <voltage-level> <current-limit>

# Example: ./lsi-ivi-dc-power-gpib-ember-set "TCPIP::127.0.0.1::serial,ACM0::INSTR" on 12 0.5

instr = vxi11.vxi11.Instrument(sys.argv[1])


if(sys.argv[2] == "off"):
    instr.write('OFF\n')
    instr.read(1024)

if len(sys.argv) == 2:
    sys.exit(0)

cmd='VSET %.02f\n'% (float(sys.argv[3]))
print(cmd)
instr.write(cmd)
instr.read(1024)
instr.read(1024)
instr.write('ISET %d\n'%(int(1000*float(sys.argv[4]))))
instr.read(1024)
instr.read(1024)

if(sys.argv[2] == "on"):
    instr.write('ON\n')
    instr.read(1024)
