#!/bin/bash

echo -n '<cameras xmlns="urn:lsi:params:xml:ns:yang:lsi-camera"><camera><name>video0</name>'
echo -n '<image>'
#ffmpeg -f video4linux2 -i /dev/video0 -ss 1 -vframes 1 1.jpg
#base64 --wrap=0 1.jpg
v4l2-ctl --device /dev/video0 --set-fmt-video=width=640,height=480,pixelformat=YUYV --stream-mmap --stream-to='-' --stream-count=1 | dd conv=swab | convert -verbose -size 640x480 UYVY:- jpeg:- | base64 --wrap=0
echo -n '</image></camera></cameras>'

