#!/bin/bash

# Usage: ./lsi-ivi-scope-acquisition-start-alsa <sample-rate> <samples> <trigger-source> <trigger-slope> <trigger-level> <ch1-name> <ch1-range> <ch1-params> ... <chN-name> <chN-range> <chN-params>
# Example: ./lsi-ivi-scope-acquisition-start-alsa 480000 48000 - - - "hw:CODEC,0" 4 "-c 2 -f S16_LE"


rm -f /tmp/${1}-signal.wav
echo "-D $6 -r ${2%.*} -s $1 $8 /tmp/$6-signal.wav" | xargs arecord &
