#!/usr/bin/python3

import datetime
import serial
import time

def state():
	# clear read pipe
	ser.timeout=0
	data = ser.read(1000)
	print(data)
	ser.timeout=None
	# status
	ser.write(b'\x8E\x00')
	data = ser.read(26)
	print(data)
	print(data[16])
	print("charge   =%05d mAh" %(data[22]*256*data[23]))
	print("capacity =%05d mAh" %(data[24]*256*data[25]))
	return (data[16])


# Open a serial connection to Roomba
ser = serial.Serial(port='/dev/ttyUSB0', baudrate=115200)



state()


print("docking")
ser.write(b'\x83') #SAFE
time.sleep(0.1)
ser.write(b'\x8F') #DOCK
time.sleep(0.1)

charging=0
while(1):
	s=state()
	print(s)
	if(s!=0):
		charging=charging+1
		if(charging==10):
			break

	print("charging=%d" %(charging))

	time.sleep(1)


ser.write(b'\x85') #POWER
time.sleep(3)
state()

# Close the serial port; we're done for now.
ser.close()

