#!/usr/bin/python3
import sys
import time
import vxi11

# Usage: ./lsi-ivi-dc-power-gpib-e364xa-get <visa-resource-name>

# Example: ./lsi-ivi-dc-power-gpib-e364xa-get "TCPIP::192.168.14.20::gpib,2::INSTR"

#<outputs-state xmlns="urn:lsi:params:xml:ns:yang:ivi-dc-power">
#<output><name>out1</name><measurement><voltage>0.004252079</voltage><current>-0.000072001</current></measurement></output>
#<output><name>out2</name><measurement><voltage>0.002100524</voltage><current>-0.000328174</current></measurement></output>
#</outputs-state>


instr = vxi11.vxi11.Instrument(sys.argv[1])



instr.write('INSTRUMENT:SELECT out1')
reply = instr.ask("Measure:Current?")
current1=float(reply)

reply = instr.ask("Measure:Voltage?")
voltage1=float(reply)

instr.write('INSTRUMENT:SELECT out2')
reply = instr.ask("Measure:Current?")
current2=float(reply)

reply = instr.ask("Measure:Voltage?")
voltage2=float(reply)

print("""<outputs-state xmlns="urn:lsi:params:xml:ns:yang:ivi-dc-power">""")
print("""<output><name>out1</name><measurement><voltage>%.9f</voltage><current>%.9f</current></measurement></output>"""%(voltage1, current1))
print("""<output><name>out2</name><measurement><voltage>%.9f</voltage><current>%.9f</current></measurement></output>"""%(voltage2, current2))
print("""</outputs-state>""")
