#!/usr/bin/python3

global args
args=None

import sys
import time
import sys
import os
import datetime
import vxi11

import numpy as np
import scipy.io.wavfile as wf

# Usage: ./lsi-ivi-scope-acquisition-start-dummy <sample-rate> <samples> <trigger-source> <trigger-slope> <trigger-level> <ch1-name> <ch1-range> <ch1-params> ... <chN-name> <chN-range> <chN-params>

# Example: ./lsi-ivi-scope-acquisition-start-dummy 100000 1000 ch1 positive 0.0 ch1 10 - ch2 1 -

sample_rate=float(sys.argv[1])
samples=int(sys.argv[2])
trigger_source=sys.argv[3]
trigger_slope=sys.argv[4]
trigger_level=float(sys.argv[5])


channels_num = int((len(sys.argv)-6)/3)
print (channels_num)
for i in range(0,channels_num):
    name=sys.argv[6+i*3]
    voltage_range=float(sys.argv[6+i*3+1])
    params=sys.argv[6+i*3+2]

    signal_samples = np.linspace(0, samples/sample_rate, int(samples), endpoint=False)
    signal = np.sin(2 * np.pi * 1000 * signal_samples)
    #signal *= (voltage_range/2)
    signal *= 32767
    print(len(signal))
    wf.write("/tmp/%s-signal.wav"%(name), int(sample_rate), np.int16(signal))

time.sleep(samples/sample_rate)


sys.exit(0)
