#!/usr/bin/python3
import sys
import time
import vxi11

# Usage: ./lsi-ivi-dc-power-gpib-e364xa-get <visa-resource-name>

# Example: ./lsi-ivi-dc-power-gpib-e364xa-get "TCPIP::192.168.14.20::gpib,2::INSTR"

#<outputs-state xmlns="urn:lsi:params:xml:ns:yang:ivi-dc-power">
#<output><name>out1</name><measurement><voltage>0.004252079</voltage><current>-0.000072001</current></measurement></output>
#<output><name>out2</name><measurement><voltage>0.002100524</voltage><current>-0.000328174</current></measurement></output>
#</outputs-state>


instr = vxi11.vxi11.Instrument(sys.argv[1])

instr.write('IGET\n')
reply = instr.read(1024)
reply = instr.read(1024)
current1=float(reply)
instr.write('VGET\n')
reply = instr.read(1024)
reply = instr.read(1024)
voltage1=float(reply)


print("""<outputs-state xmlns="urn:lsi:params:xml:ns:yang:ivi-dc-power">""")
print("""<output><name>out1</name><measurement><voltage>%.9f</voltage><current>%.9f</current></measurement></output>"""%(voltage1, float(current1)/1000))
print("""</outputs-state>""")
