#!/bin/bash

value=`sudo pcsensor  -p -c`
value_int=`echo "scale=0; $value*100/1" | bc -l`
echo -n '<thermometers xmlns="urn:lsi:params:xml:ns:yang:thermometers"><thermometer><name>th0</name><value>'${value_int}'</value></thermometer></thermometers>'
